# Generated by Django 3.1.1 on 2020-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200918_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatnew',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatnew',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.MessageNew'),
        ),
    ]
